### <p style="text-align: right;"> &#9999; Type your name here</p>

## 16B arange and linspace ##

Now that you have some of the basic concepts of an array, such as all elements need to be the same type and that they have dimensions (remember, from the error code discussion).

Let's explore how to create arrays. There are two methods that we will be using first. 
- `linspace`
- `arange`

Look up the difference in numpy.linspace and numpy.arange. It might help you to look up sample code in each.

Describe what you find here: 
&#9999;



In [7]:
# comparing arange to linspace
import numpy as np

arr1 = np.arange(1,10,2)
arr2 = np.linspace(7,10,10)

print(arr1,arr2)


[1 3 5 7 9] [ 7.          7.33333333  7.66666667  8.          8.33333333  8.66666667
  9.          9.33333333  9.66666667 10.        ]


In [12]:
# comparing arange to linspace
import numpy as np

arr1 = np.arange(1,10,2)
arr2 = np.linspace(1,10,10)

arr2[2] = arr2[3]-arr2[1]
arr1[2] = arr1[3]-arr1[1]

print(arr1,arr2)


[1 3 4 7 9] [ 1.  2.  2.  4.  5.  6.  7.  8.  9. 10.]


Both `linspace` and `arange` take three arguments (the values in the parentheses (...)). 
Try to modify the arguments to determine what each of the three values mean in context. 
Provide some examples to support your conclusions. Remember to use np.arange and np.linspace in your examples. Use comments to explain what eaach argument represents.

&#9999;&nbsp; Write you examples and explanatory comments in the cell below.

In [19]:
# Put your example 1 and comments here

arr1 = np.arange(1,10,2) #control array
print(arr1)
arr2 = np.arange(1,10,3) #changing third arg to test
print(arr2)
# last argument is step value

arr1 = np.arange(1,12,1) # control array
print(arr1)
arr2 = np.arange(1,14,1) # changing third argument to test
print(arr2)
# second arguemnt is the range of values that it goes to 

arr1 = np.arange(2,12,1) # control array
print(arr1)
arr2 = np.arange(4,12,1) # changing first argument to test
print(arr2)
# first argument defines where the array starts

[1 3 5 7 9]
[1 4 7]
[ 1  2  3  4  5  6  7  8  9 10 11]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 2  3  4  5  6  7  8  9 10 11]
[ 4  5  6  7  8  9 10 11]


In [25]:
# Put your example 2 and comments here
a1 = np.linspace(1,10,12) # control array
print(a1)
a2 = np.linspace(2,10,12) # changing first argument to test
print(a2)

[ 1.          1.81818182  2.63636364  3.45454545  4.27272727  5.09090909
  5.90909091  6.72727273  7.54545455  8.36363636  9.18181818 10.        ]
[ 2.          2.72727273  3.45454545  4.18181818  4.90909091  5.63636364
  6.36363636  7.09090909  7.81818182  8.54545455  9.27272727 10.        ]


In [ ]:
# type your code here


In [ ]:
# let's reverse the order for arange


In [ ]:
# Type your code here. Remember to comment in your observations.


&#9999;&nbsp; 

In [28]:
# type in your code here

a1 = np.arange(300)
print(a1)
a2 = np.linspace(20)
print(a2)
#linspace needs more than one argument, but arange doesnt. arange takes the one argumenet as the range.

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

TypeError: linspace() missing 1 required positional argument: 'stop'

&#9999;&nbsp; 

In [ ]:
# Type your code here.


Both np.linspace and np.arange are best suited for specific situations. Based on what you understand of these two commands, when do you think you would use one over the other? Answer it is the cell below.

&#9999;&nbsp;

